version: '3.3'

services:
# #--------TRAEFIK SERVICE--------------
   traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    restart: always
    command:
     # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=$ADMIN_MAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--serversTransport.insecureSkipVerify=true"
     labels:
      - "traefik.http.routers.traefik.rule=Host(`$MONITOR_DOMAIN`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"

    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_ssl:/letsencrypt
      - traefik_tmp:/tmp
      
#--------DB SERVICE--------------
   db:
     image: mysql:5.7
     container_name: "mysql"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
       MYSQL_DATABASE: $DB_DATABASE
       MYSQL_USER: $DB_USER
       MYSQL_PASSWORD: $DB_PASSWORD
     labels:
      - "traefik.enable=false" 
    




#--------WORDPRESS SERVICE--------------
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: "wordpress"
     restart: always
     volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wp-content:/var/www/html/wp-content
     ports:
      - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: $DB_USER
       WORDPRESS_DB_PASSWORD: $DB_PASSWORD
       WORDPRESS_DB_NAME: $DB_DATABASE
     labels:
      - "traefik.http.routers.wordpress.rule=Host(`$WORDPRESS_DOMAIN`)"
      # - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.enable=true"
       
       
       
#--------PHPMYADMIN SERVICE--------------
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_PORT=3306
    restart: always
    volumes:
     - /sessions
    labels:
     - "traefik.http.routers.phpmyadmin.rule=Host(`$DB_DOMAIN`)"
    #  - "traefik.http.routers.phpmyadmin.entrypoints=web"
     - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
     - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
     - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
     - "traefik.enable=true"
     
volumes:
    db_data: {}
    traefik_ssl:
    traefik_tmp:
    wp-content:
